services:
  - type: web
    name: school-quiz-game
    env: node
    buildCommand: |
      npm install
      cd admin-panel && npm install && npm run build
      cd .. && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 16.20.0
      - key: NODE_ENV
        value: production

  - type: static-site
    name: school-quiz-game
    env: static
    buildCommand: chmod +x public/render-build-static.sh && ./public/render-build-static.sh
    publishPath: ./build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_VERSION
        value: 16.20.0

  - type: static-site
    name: school-quiz-admin
    env: static
    buildCommand: cd admin-panel && npm install && CI=false npm run build
    publishPath: ./admin-panel/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_VERSION
        value: 16.20.0 