services:
  - type: web
    name: school-quiz-game-api
    env: node
    buildCommand: cd server && npm install
    startCommand: node server/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000

  - type: static-site
    name: school-quiz-game
    env: static
    buildCommand: chmod +x public/render-build-static.sh && ./public/render-build-static.sh
    publishPath: ./build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_VERSION
        value: 16.x

  - type: static-site
    name: school-quiz-admin
    env: static
    buildCommand: cd admin-panel && npm install && npm run build
    publishPath: ./admin-panel/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_VERSION
        value: 16.x 