services:
  - type: web
    name: school-quiz-game
    env: static
    buildCommand: npm run render-build
    staticPublishPath: ./server/build
    envVars:
      - key: NODE_VERSION
        value: 16.x
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 